-- =========================================================
-- schema.sql
-- Table creation script for H2 based on JPA entities
-- =========================================================

-- 1. ADMIN Table
-- Maps to com.san.system.model.Admin
-- Primary Key: email_id
CREATE TABLE IF NOT EXISTS admin (
    email_id VARCHAR(255) NOT NULL,
    password VARCHAR(255),
    PRIMARY KEY (email_id)
);

-- 2. FACULTY Table
-- Maps to com.san.system.model.Faculty
-- Primary Key: id (Auto-incremented)
-- Unique Constraint: email
CREATE TABLE IF NOT EXISTS faculty (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    department VARCHAR(255),
    email VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    qr_data VARCHAR(255),
    UNIQUE (email)
);

-- 3. STUDENTS Table
-- Maps to com.san.system.model.Student
-- Primary Key: id (Auto-incremented)
-- Unique Constraint: email
CREATE TABLE IF NOT EXISTS students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    department VARCHAR(255),
    email VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    UNIQUE (email)
);